project:
  type: website
  output-dir: docs

website:
  title: "JCodes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JamesEmi
      - icon: twitter
        href: https://twitter.com/JamesEmilian2
format:
  html:
    theme: journal
    css: styles.css


